version: '3.7'

services:
  scrapper:
    build: ./scrapper/
    ports:
      - 4444:4444
    volumes: 
      - ./artifacts:/code/artifacts
    environment:
      SCRAPPER_ENV: DOCKER
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./scrapper/.env_db



volumes:
  postgres_data: