version: '3.7'

services:
  scrapper:
    build: 
      context: ./
      dockerfile: ./src/docker/Dockerfile
    ports:
      - 4444:4444
    volumes: 
      - ./artifacts:/code/artifacts
    environment:
      SCRAPPER_ENV: DOCKER
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart:
      always

volumes:
  postgres_data:
